# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/image_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_time_series_viewer(object):
    def setupUi(self, time_series_viewer):
        time_series_viewer.setObjectName("time_series_viewer")
        time_series_viewer.resize(600, 600)
        self.layoutWidget = QtWidgets.QWidget(time_series_viewer)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 10, 581, 581))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image = ImageView(self.layoutWidget)
        self.image.setObjectName("image")
        self.verticalLayout.addWidget(self.image)
        self.frame_slider = QtWidgets.QSlider(self.layoutWidget)
        self.frame_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.verticalLayout.addWidget(self.frame_slider)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_label = QtWidgets.QLabel(self.layoutWidget)
        self.frame_label.setObjectName("frame_label")
        self.horizontalLayout_2.addWidget(self.frame_label)
        self.image_label = QtWidgets.QLabel(self.layoutWidget)
        self.image_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.image_label.setObjectName("image_label")
        self.horizontalLayout_2.addWidget(self.image_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 20)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(time_series_viewer)
        QtCore.QMetaObject.connectSlotsByName(time_series_viewer)

    def retranslateUi(self, time_series_viewer):
        _translate = QtCore.QCoreApplication.translate
        time_series_viewer.setWindowTitle(_translate("time_series_viewer", "Form"))
        self.frame_label.setText(_translate("time_series_viewer", "frame: 0"))
        self.image_label.setText(_translate("time_series_viewer", "x: 0, y: 0, value: 0"))
from pyqtgraph import ImageView
