# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frappe/ui/metadata_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageMetadata(object):
    def setupUi(self, ImageMetadata):
        ImageMetadata.setObjectName("ImageMetadata")
        ImageMetadata.resize(450, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImageMetadata)
        self.verticalLayout.setObjectName("verticalLayout")
        self.metadata_tree = QtWidgets.QTreeWidget(ImageMetadata)
        self.metadata_tree.setObjectName("metadata_tree")
        self.verticalLayout.addWidget(self.metadata_tree)

        self.retranslateUi(ImageMetadata)
        QtCore.QMetaObject.connectSlotsByName(ImageMetadata)

    def retranslateUi(self, ImageMetadata):
        _translate = QtCore.QCoreApplication.translate
        ImageMetadata.setWindowTitle(_translate("ImageMetadata", "Dialog"))
        self.metadata_tree.headerItem().setText(0, _translate("ImageMetadata", "Tag"))
        self.metadata_tree.headerItem().setText(1, _translate("ImageMetadata", "Value"))
