# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frappe/ui/track_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 485)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.track_plot = PlotWidget(self.centralwidget)
        self.track_plot.setGeometry(QtCore.QRect(280, 30, 561, 371))
        self.track_plot.setObjectName("track_plot")
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setGeometry(QtCore.QRect(20, 10, 113, 32))
        self.play_button.setObjectName("play_button")
        self.pause_button = QtWidgets.QPushButton(self.centralwidget)
        self.pause_button.setGeometry(QtCore.QRect(150, 10, 113, 32))
        self.pause_button.setObjectName("pause_button")
        self.track_table = QtWidgets.QTableWidget(self.centralwidget)
        self.track_table.setGeometry(QtCore.QRect(10, 150, 261, 271))
        self.track_table.setObjectName("track_table")
        self.track_table.setColumnCount(4)
        self.track_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.track_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.track_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.track_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.track_table.setHorizontalHeaderItem(3, item)
        self.localizations_per_second = QtWidgets.QLineEdit(self.centralwidget)
        self.localizations_per_second.setGeometry(QtCore.QRect(180, 40, 71, 21))
        self.localizations_per_second.setObjectName("localizations_per_second")
        self.localizations_per_second_label = QtWidgets.QLabel(self.centralwidget)
        self.localizations_per_second_label.setGeometry(QtCore.QRect(10, 40, 161, 16))
        self.localizations_per_second_label.setObjectName("localizations_per_second_label")
        self.localizations_to_display_label = QtWidgets.QLabel(self.centralwidget)
        self.localizations_to_display_label.setGeometry(QtCore.QRect(10, 70, 161, 16))
        self.localizations_to_display_label.setObjectName("localizations_to_display_label")
        self.localizations_to_display = QtWidgets.QLineEdit(self.centralwidget)
        self.localizations_to_display.setGeometry(QtCore.QRect(180, 70, 71, 21))
        self.localizations_to_display.setObjectName("localizations_to_display")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.play_button.setText(_translate("MainWindow", "Play"))
        self.pause_button.setText(_translate("MainWindow", "Pause"))
        item = self.track_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Track ID"))
        item = self.track_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Show"))
        item = self.track_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Frame start"))
        item = self.track_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Frame end"))
        self.localizations_per_second_label.setText(_translate("MainWindow", "Localizations per second:"))
        self.localizations_to_display_label.setText(_translate("MainWindow", "Localizations to display:"))
from pyqtgraph import PlotWidget
