# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frappe/ui/track_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 485)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.track_plot = PlotWidget(self.centralwidget)
        self.track_plot.setGeometry(QtCore.QRect(270, 40, 561, 371))
        self.track_plot.setObjectName("track_plot")
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setGeometry(QtCore.QRect(0, 10, 91, 32))
        self.play_button.setObjectName("play_button")
        self.pause_button = QtWidgets.QPushButton(self.centralwidget)
        self.pause_button.setGeometry(QtCore.QRect(90, 10, 91, 32))
        self.pause_button.setObjectName("pause_button")
        self.track_table = QtWidgets.QTableWidget(self.centralwidget)
        self.track_table.setGeometry(QtCore.QRect(10, 150, 261, 271))
        self.track_table.setObjectName("track_table")
        self.track_table.setColumnCount(4)
        self.track_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.track_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.track_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.track_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.track_table.setHorizontalHeaderItem(3, item)
        self.localizations_per_second = QtWidgets.QLineEdit(self.centralwidget)
        self.localizations_per_second.setGeometry(QtCore.QRect(180, 40, 71, 21))
        self.localizations_per_second.setObjectName("localizations_per_second")
        self.localizations_per_second_label = QtWidgets.QLabel(self.centralwidget)
        self.localizations_per_second_label.setGeometry(QtCore.QRect(10, 40, 161, 16))
        self.localizations_per_second_label.setObjectName("localizations_per_second_label")
        self.localizations_to_display_label = QtWidgets.QLabel(self.centralwidget)
        self.localizations_to_display_label.setGeometry(QtCore.QRect(10, 70, 161, 16))
        self.localizations_to_display_label.setObjectName("localizations_to_display_label")
        self.localizations_to_display = QtWidgets.QLineEdit(self.centralwidget)
        self.localizations_to_display.setGeometry(QtCore.QRect(180, 70, 71, 21))
        self.localizations_to_display.setObjectName("localizations_to_display")
        self.update_rate_label = QtWidgets.QLabel(self.centralwidget)
        self.update_rate_label.setGeometry(QtCore.QRect(280, 10, 241, 16))
        self.update_rate_label.setObjectName("update_rate_label")
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setGeometry(QtCore.QRect(550, 10, 241, 16))
        self.time_label.setObjectName("time_label")
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(180, 10, 91, 32))
        self.reset_button.setObjectName("reset_button")
        self.show_scale_bar = QtWidgets.QCheckBox(self.centralwidget)
        self.show_scale_bar.setGeometry(QtCore.QRect(10, 100, 121, 20))
        self.show_scale_bar.setObjectName("show_scale_bar")
        self.bar_length = QtWidgets.QLineEdit(self.centralwidget)
        self.bar_length.setEnabled(False)
        self.bar_length.setGeometry(QtCore.QRect(130, 100, 91, 21))
        self.bar_length.setReadOnly(False)
        self.bar_length.setObjectName("bar_length")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.play_button.setText(_translate("MainWindow", "Play"))
        self.pause_button.setText(_translate("MainWindow", "Stop"))
        item = self.track_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Track ID"))
        item = self.track_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Show"))
        item = self.track_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Frame start"))
        item = self.track_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Frame end"))
        self.localizations_per_second_label.setText(_translate("MainWindow", "Localizations per update:"))
        self.localizations_to_display_label.setText(_translate("MainWindow", "Localizations to display:"))
        self.update_rate_label.setText(_translate("MainWindow", "Average update rate (1/s):"))
        self.time_label.setText(_translate("MainWindow", "Time (ms):"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
        self.show_scale_bar.setText(_translate("MainWindow", "Show scale bar"))
        self.bar_length.setText(_translate("MainWindow", "10"))
from pyqtgraph import PlotWidget
