# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/multi_slider.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets
from frappe.pyuic5_output import slider


class MultiSlider(QtWidgets.QWidget):

    def __init__(self):
        pass


class LabelSlider(QtWidgets.QWidget):

    def __init__(self, parent=None, *args, **kwargs):
        super(LabelSlider, self).__init__(parent, *args, **kwargs)
        self._label = ""
        self.ui = slider.Ui_Form()
        # self.widget = QtWidgets.QWidget(parent)
        self.ui.setupUi(self)
        self.ui.slider.valueChanged['int'].connect(
            lambda x: self.ui.slider_label.setText(f"{self.label}: {x}")
        )

    @property
    def label(self):
        return self._label

    @label.setter
    def label(self, new_label):
        self._label = new_label
        self.ui.slider_label.setText(f"{self.label}: {self.ui.slider.value()}")

    def advance_frame(self, n=1):
        if self.isVisible():
            self.ui.slider.setValue(self.ui.slider.value() + n)

    def set_maximum(self, maximum_value):
        self.ui.slider.setMaximum(maximum_value)
